# Generated by Django 4.1.4 on 2022-12-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Phones & Tablets", "Phones & Tablets"),
                            ("PCs & Laptops", "PCs & Laptops"),
                            ("TV & Audio", "TV & Audio"),
                            ("Household Appliances", "Household Appliances"),
                            ("Large Appliances", "Large Appliances"),
                            ("Health & Beauty", "Health & Beauty"),
                            ("Baby Care", "Baby Care"),
                            ("Camping & Outdoors", "Camping & Outdoors"),
                            ("Cycling", "Cycling"),
                            ("Exercise & Fitness", "Exercise & Fitness"),
                            ("Sport Apparel", "Sport Apparel"),
                            ("Sport Shoes", "Sport Shoes"),
                            ("Toys & Games", "Toys & Games"),
                            ("Baby Clothing & Shoes", "Baby Clothing & Shoes"),
                            ("Women Apparel & Shoes", " Women Apparel & Shoes"),
                            ("Men Apparel & Shoes", " Men Apparel & Shoes"),
                            ("Watches", "Watches"),
                            ("Jewellery", "Jewellery"),
                            ("All for Home", "All for Home"),
                            ("All for Garden", "All for Garden"),
                            ("All for Pets", "All for Pets"),
                            ("Other", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
            ],
            options={"verbose_name_plural": "Categories",},
        ),
    ]
