# Generated by Django 4.1.4 on 2022-12-10 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_photos"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="photos", options={"verbose_name_plural": "Photos"},
        ),
    ]
