# Generated by Django 4.1.4 on 2022-12-11 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_alter_product_product_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product", options={"ordering": ("-date_of_publication",)},
        ),
    ]
