# Generated by Django 4.1.4 on 2022-12-12 00:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_alter_product_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_name",
            field=models.CharField(
                max_length=35,
                validators=[django.core.validators.MinLengthValidator(2)],
                verbose_name="Product Name",
            ),
        ),
    ]
